apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tech-challenge-db
  namespace: tech-challenge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: tech-challenge-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOST: "{{ .DB_HOST }}"
        DB_PORT: "{{ .DB_PORT }}"
        DB_NAME: "{{ .DB_NAME }}"
        DB_USER: "{{ .DB_USER }}"
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DATABASE_URL: >-
          mysql+asyncmy://{{ .DB_USER }}:{{ .DB_PASSWORD }}@{{ .DB_HOST }}:{{ .DB_PORT }}/{{ .DB_NAME }}
        MIGRATION_DATABASE_URL: >-
          mysql+pymysql://{{ .DB_USER }}:{{ .DB_PASSWORD }}@{{ .DB_HOST }}:{{ .DB_PORT }}/{{ .DB_NAME }}

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: tech-challenge/rds/mysql/app-credentials
        property: host

    - secretKey: DB_PORT
      remoteRef:
        key: tech-challenge/rds/mysql/app-credentials
        property: port

    - secretKey: DB_NAME
      remoteRef:
        key: tech-challenge/rds/mysql/app-credentials
        property: dbname

    - secretKey: DB_USER
      remoteRef:
        key: tech-challenge/rds/mysql/app-credentials
        property: username

    - secretKey: DB_PASSWORD
      remoteRef:
        key: tech-challenge/rds/mysql/app-credentials
        property: password
