apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tech-challenge-db
  namespace: tech-challenge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: tech-challenge-db
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          mysql+pymysql://{{ .DB_USER }}:{{ .DB_PASSWORD }}@{{ .DB_HOST }}:{{ .DB_PORT }}/{{ .DB_NAME }}

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: tech-challenge/dev/db
        property: DB_HOST

    - secretKey: DB_USER
      remoteRef:
        key: tech-challenge/dev/db
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: tech-challenge/dev/db
        property: DB_PASSWORD

    - secretKey: DB_PORT
      remoteRef:
        key: tech-challenge/dev/db
        property: DB_PORT

    - secretKey: DB_NAME
      remoteRef:
        key: tech-challenge/dev/db
        property: DB_NAME
