apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: tech-challenge
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::209757840409:role/tech-challenge-dev-eks-secrets-manager-role
automountServiceAccountToken: true
