apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tech-challenge-db
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager
  target:
    name: tech-challenge-db
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DB_HOST

    - secretKey: DB_PORT
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DB_PORT

    - secretKey: DB_NAME
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DB_NAME

    - secretKey: DB_USER
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DB_USER

    - secretKey: DB_PASSWORD
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DB_PASSWORD

    - secretKey: DATABASE_URL
      remoteRef:
        key: tech-challenge/rds-mysql
        property: DATABASE_URL
